Updates to configure:  look for basic support programs, warn and bail if not found.  Transparent support for Cygwin autoconf-2.69.  Attempt to fix libpng includes in win-builds.

diff --git a/Makefile.sample b/Makefile.sample
--- a/Makefile.sample
+++ b/Makefile.sample
@@ -45,11 +45,6 @@
 #MINGW  = --enable-mingw=/usr/local/win-builds
 #GTKLOC = --enable-gtk2=/usr/local/gtk2-bundle/bin
 
-# NOTE:  We need "autoconf" in Windows, Cygwin provides "autoconf-2.69".
-# To fix, from a CMD window in c:\cygwin64\bin, give
-#  mklink /j autoconf autoconf-2.69
-# This creates a symbolic link named "autoconf" to autoconf-2.69.
-
 # If you don't want to build all the tools, you can choose what to
 # build below.  The xt_base is required for everything, other
 # dependencies are represented by the two lines below.  You can change
@@ -74,7 +69,22 @@ FLAGFILE = .configured
 
 config:
 	@if [ ! -f $(FLAGFILE) ]; then \
-	    (cd xt_base; autoconf; ./configure $(CFARGS)); \
+	    command -v autoconf; \
+	    if [ $$? = 0 ]; then \
+	        (cd xt_base; autoconf; ./configure $(CFARGS)); \
+	        if [ $$? != 0 ]; then exit 1; fi; \
+	    else \
+	        command -v autoconf-2.69; \
+                if [ $$? = 0 ]; then \
+                    (cd xt_base; autoconf-2.69; ./configure $(CFARGS)); \
+                    if [ $$? != 0 ]; then exit 1; fi; \
+                else \
+	            echo \
+"  Error: the autoconf program (autoconf-2.69 in Cygwin) is not found"; \
+	            echo "  and is required."; \
+	            exit 1; \
+	        fi; \
+	    fi; \
 	    touch $(FLAGFILE); \
 	fi
 	(${MAKE} depend)
@@ -82,9 +92,6 @@ config:
 reconfig:
 	-@rm -f $(FLAGFILE)
 	$(MAKE) config
-
-testcfg:
-	cd xt_base; $(MAKE) distclean; autoconf; ./configure $(CFARGS)
 
 all: config
 	-@for a in $(SUBDIRS); do \
diff --git a/xt_base/configure.in b/xt_base/configure.in
--- a/xt_base/configure.in
+++ b/xt_base/configure.in
@@ -213,38 +213,79 @@ dnl ***
 dnl *** Check operating system and build environment
 dnl ***
 
+AC_PATH_PROG(PATCH, patch, "")
+if test -z "$PATCH"; then
+    echo "  Error: the \"patch\" program is required and not found."
+    exit 1
+fi
+AC_PATH_PROG(FLEX, flex, "")
+if test -z "$FLEX"; then
+    echo "  Error: the \"flex\" program is required and not found."
+    exit 1
+fi
+AC_PATH_PROG(BISON, bison, "")
+if test -z "$BISON"; then
+    echo "  Error: the \"bison\" program is required and not found."
+    exit 1
+fi
+AC_PATH_PROG(acf1, autoconf, "")
+if test -z "$acf1"; then
+    AC_PATH_PROG(acf2, autoconf-2.69, "")
+    if test -z "$acf2"; then
+        echo "  Error: the \"autoconf\" program (\"autoconf-2.69\" in Cygwin)" 
+        echo "  is required and not found."
+        exit 1
+    else
+        ACONF=$acf2
+    fi
+else
+    ACONF=$acf1
+fi
+AC_PATH_PROG(AR, ar, "")
+if test -z "$AR"; then
+    echo "  Error: the \"ar\" program is required and not found."
+    exit 1
+fi
+AC_PATH_PROG(LD, ld, "")
+AC_PATH_PROG(RANLIB, ranlib, "")
+
 sys_os=`uname`
-case $sys_os in
-CYGWIN*)
+if test ${sys_os:0:6} = CYGWIN; then
     mingw=yes
     sys_os="CYGWIN"
     CC=$mingw_dir/bin/gcc
     CXX=$mingw_dir/bin/g++
-    WINDRES=$mingw_dir/bin/windres
     RESOURCE=resource.o
-    AR=$mingw_dir/bin/ar
-    RANLIB=$mingw_dir/bin/ranlib
-    LD=$mingw_dir/bin/ld
 dnl # static link avoids libwinpthread-1.dll dependence
     WINPTHREADFIX="-static"
-    ;;
-*)
-    if test "$AR" = ""; then
-        AR=ar
+
+dnl # Win-builds has the png include files in a weird place, where they
+dnl # won't be found.  This will prevent png image support unless
+dnl # corrected.  Here we look for this and do the correction if
+dnl # possible.  If the operation fails (permission problem) the user
+dnl # must do this by hand.
+    if test ! -f $mingw_dir/include/png.h -a  \
+        -f $mingw_dir/include/libpng14/png.h; then
+        echo "Configuring win-builds:"
+        echo "cp -f $mingw_dir/include/libpng14/png.h $mingw_dir/include"
+        cp -f $mingw_dir/include/libpng14/png.h $mingw_dir/include
+        if test $? != 0; then
+            echo "Didn't work, do this by hand.  See README file."
+            exit 1
+        fi
+        echo "cp -f $mingw_dir/include/libpng14/pngconf.h $mingw_dir/include"
+        cp -f $mingw_dir/include/libpng14/pngconf.h $mingw_dir/include
     fi
-    if test "$RANLIB" = ""; then
-        AC_PROG_RANLIB
-    fi
-    if test "$LD" = ""; then
-        LD=ld
-    fi
-    ;;
-esac
+
+    AC_PATH_PROG(WINDRES, windres, "")
+fi
+
+AC_SUBST(ACONF)
+AC_SUBST(AR)
+AC_SUBST(LD)
+AC_SUBST(RANLIB)
 AC_SUBST(WINDRES)
 AC_SUBST(RESOURCE)
-AC_SUBST(AR)
-AC_SUBST(RANLIB)
-AC_SUBST(LD)
 AC_SUBST(WINPTHREADFIX)
 
 AC_PROG_CC
