Integation of old QT code, in progress.

diff --git a/xt_base/configure.in b/xt_base/configure.in
--- a/xt_base/configure.in
+++ b/xt_base/configure.in
@@ -1,4 +1,4 @@
-dnl Configure input script for XicTools.
+nl Configure input script for XicTools.
 dnl Process this file with autoconf to produce a configure script.
 dnl Copyright (c) Whiteley Research Inc, 2002
 dnl $Id: configure.in,v 1.233 2016/09/28 22:49:23 stevew Exp $
@@ -205,8 +205,24 @@ if test $enable_qt5 != yes -a $enable_qt5 != no; then
     qtloc=$enable_qt5
     qtlocd="$enable_qt5/"
     grpkg="QT5"
+elif test $enable_qt5 == yes; then
+    grpkg="QT5"
 fi
 )
+
+if test -z $grpkg; then
+dnl --enable-qt6[=config_dir]
+dnl link with qt6
+AC_ARG_ENABLE(qt6,   [  ]--enable-qt6[[=config_dir]]            link with qt6,
+if test $enable_qt6 != yes -a $enable_qt6 != no; then
+    qtloc=$enable_qt6
+    qtlocd="$enable_qt6/"
+    grpkg="QT6"
+elif test $enable_qt6 == yes; then
+    grpkg="QT6"
+fi
+)
+fi
 
 if test -z $grpkg; then
 dnl --enable-gtk2[=config_dir]
@@ -678,7 +694,6 @@ if test $valgrind = yes; then
    CFLAGS_SG="-O0 -g $c_flags"
    CFLAGS="-O0 $c_flags"
 fi
-
 AC_SUBST(CFLAGS)
 AC_SUBST(CFLAGS_S)
 AC_SUBST(CFLAGSG)
@@ -693,7 +708,10 @@ dnl ***
 dnl *** Graphical interface configuration
 dnl ***
 
-if test $grpkg = "QT5"; then
+if test -z "$grpkg"; then
+   echo "No graphics toolkit specified, fatal error."
+   exit 1;
+elif test $grpkg == QT5 -o $grpkg == QT6 ; then
     QTBASE=$qtloc
 
     tmpdir="/tmp/__tmp__"
@@ -702,53 +720,69 @@ if test $grpkg = "QT5"; then
     cd $tmpdir
     touch empty.cc
     $QTBASE/bin/qmake -project
-    $QTBASE/bin/qmake "QT += xml opengl"
+    $QTBASE/bin/qmake "QT += widgets xml opengl printsupport"
     cd $cwd
 
     has_qt=no
     if test -f $tmpdir/Makefile; then
         has_qt=yes
 
-        cf=`grep '^CXXFLAGS' $tmpdir/Makefile`
-        set $cf
+        defines=`grep '^DEFINES' $tmpdir/Makefile`
+        set $defines
         while test x"$1" != x; do
             y=`echo $1 |grep "^-D"`
             if test x"$y" != x; then
+                QT_DEFINES="$QT_DEFINES $1"
+            fi
+            shift
+        done
+        echo "QT_DEFINES=$QT_DEFINES"
+
+        cxxflags=`grep '^CXXFLAGS' $tmpdir/Makefile`
+        set $cxxflags
+        shift
+        shift
+        while test x"$1" != x; do
+            if test "$1" != '$(DEFINES)'; then
                 QT_CFLAGS="$QT_CFLAGS $1"
             fi
             shift
         done
         echo "QT_CFLAGS=$QT_CFLAGS"
 
-        ip=`grep '^INCPATH' $tmpdir/Makefile`
-        set $ip
+        incpath=`grep '^INCPATH' $tmpdir/Makefile`
+        set $incpath
+        QT_INCLUDE="-I$QTBASE/include"
+        if test $OSNAME == Darwin ; then
+dnl MacPorts, needed to find X11.
+            QT_INCLUDE="$QT_INCLUDE -I/opt/local/include"
+        fi
         while test x"$1" != x; do
             y=`echo $1 |grep "^-I"`
             if test x"$y" != x -a $1 != "-I."; then
-                QT_INCL="$QT_INCL $1"
+                QT_INCLUDE="$QT_INCLUDE $1"
             fi
             shift
         done
-        echo "QT_INCL=$QT_INCL"
+        echo "QT_INCLUDE=$QT_INCLUDE"
 
-        lf=`grep '^LFLAGS' $tmpdir/Makefile`
-        set $lf
+        lflags=`grep '^LFLAGS' $tmpdir/Makefile`
+        set $lflags
+        shift
+        shift
         while test x"$1" != x; do
-            y=`echo $1 |grep "^-"`
-            if test x"$y" != x; then
-                QT_LFLAGS="$QT_LFLAGS $1"
-            fi
+            QT_LFLAGS="$QT_LFLAGS $1"
             shift
         done
         echo "QT_LFLAGS=$QT_LFLAGS"
 
-        lb=`grep '^LIBS' $tmpdir/Makefile`
-        set $lb
+        libs=`grep '^LIBS' $tmpdir/Makefile`
+        set $libs
+        shift
+        shift
+        shift
         while test x"$1" != x; do
-            y=`echo $1 |grep "^-"`
-            if test x"$y" != x; then
-                QT_LIBS="$QT_LIBS $1"
-            fi
+            QT_LIBS="$QT_LIBS $1"
             shift
         done
         echo "QT_LIBS=$QT_LIBS"
@@ -762,9 +796,9 @@ if test $grpkg = "QT5"; then
 
     GRPREF=qt
     MOC="$QTBASE/bin/moc"
-    TOOLKITINC="$QT_INCL"
+    TOOLKITINC="$QT_INCLUDE"
     TOOLKITLIBS="$QT_LIBS"
-    TOOLKITCFLAGS="$QT_CFLAGS"
+    TOOLKITCFLAGS="$QT_CFLAGS $QT_DEFINES"
     TOOLKITLFLAGS="$QT_LFLAGS"
 
 elif test $grpkg == "GTK2"; then
@@ -831,6 +865,9 @@ dnl     -DGSEAL_ENABLE"
         echo "pkg-config not found"
         exit
     fi
+else
+   echo "Unknown graphics toolkit $grpkg specified, fatal error."
+   exit 1;
 fi
 
 AC_SUBST(GRPREF)
