ADMS: tweaks for 2.3.7, including configure change to use the bison in the gtk2-bundle-x11/bin for OSX.  The ancient bison provided by OSX doesn't work here.

diff --git a/xt_base/configure.in b/xt_base/configure.in
--- a/xt_base/configure.in
+++ b/xt_base/configure.in
@@ -240,16 +240,6 @@ if test -z "$PATCH"; then
     echo "  Error: the \"patch\" program is required and not found."
     exit 1
 fi
-AC_PATH_PROG(FLEX, flex, "")
-if test -z "$FLEX"; then
-    echo "  Error: the \"flex\" program is required and not found."
-    exit 1
-fi
-AC_PATH_PROG(BISON, bison, "")
-if test -z "$BISON"; then
-    echo "  Error: the \"bison\" program is required and not found."
-    exit 1
-fi
 AC_PATH_PROG(acf1, autoconf, "")
 if test -z "$acf1"; then
     AC_PATH_PROG(acf2, autoconf-2.69, "")
@@ -271,8 +261,30 @@ fi
 AC_PATH_PROG(LD, ld, "")
 AC_PATH_PROG(RANLIB, ranlib, "")
 
-NEED_FILTER=no
 sys_os=`uname`
+
+AC_PATH_PROG(FLEX, flex, "")
+if test -z "$FLEX"; then
+    echo "  Error: the \"flex\" program is required and not found."
+    exit 1
+fi
+LEX="$FLEX -l"
+if test $sys_os == "Darwin"; then
+    BISON=/usr/local/gtk2-bundle-x11/bin/bison
+else
+    AC_PATH_PROG(BISON, bison, "")
+fi
+if test -z "$BISON"; then
+    echo "  Error: the \"bison\" program is required and not found."
+    exit 1
+fi
+YACC="$BISON -y"
+AC_SUBST(LEX)
+AC_SUBST(YACC)
+AC_SUBST(FLEX)
+AC_SUBST(BISON)
+
+NEED_FILTER=no
 if test ${sys_os:0:6} = CYGWIN -o ${sys_os:0:5} = MINGW; then
     mingw=yes
 dnl # Filtering drive specifiers and linefeeds not needed in MSYS2.
@@ -335,9 +347,6 @@ AC_SUBST([NO_IGNORED_QUALIFIERS])
 
 AC_PROG_MAKE_SET
 
-LEX="flex -l"
-AC_PROG_LEX(noyywrap)
-AC_PROG_YACC
 AC_PATH_XTRA
 
 DLL_SPICE_PROG='dll-wrspice'
