Infrastructure added to make sure that copied files are the same as the source.  It was too easy to modify a local copy, which would not propagate.  Release WRspice-4.3.5, previous doc updates didn't make it into the source or packages.

diff --git a/wrspice/devlib/adms/include/Makefile b/wrspice/devlib/adms/include/Makefile
--- a/wrspice/devlib/adms/include/Makefile
+++ b/wrspice/devlib/adms/include/Makefile
@@ -25,4 +25,18 @@ input.h:        $(INCL)/include/input.h
 clean distclean:
 	-@rm -f $(SPHFILES)
 
+# Make sure that the copies are the same as the source, avoid local
+# updates that won't propagate!
+cptest::
+	@for a in $(SPHFILES); do \
+	    s1="`/usr/bin/sum $(INCL)/include/$$a`"; \
+	    s2="`/usr/bin/sum $$a`"; \
+            if [ "$$s1" != "$$s2" ]; then \
+	        echo ; \
+	        echo  "ERROR!!! $$a differs in $(INCL)/include, FIXME"; \
+	        echo ; \
+	        exit 1; \
+	    fi; \
+	done
+
 
diff --git a/wrspice/help/Makefile b/wrspice/help/Makefile
--- a/wrspice/help/Makefile
+++ b/wrspice/help/Makefile
@@ -48,3 +48,37 @@ distclean:
 check::
 	-egrep 'href="[^>"]+>' *.hlp
 
+# Make sure that the copies are the same as the source, avoid local
+# updates that won't propagate!
+cptest::
+	@for a in $(BASEFILES); do \
+	    s1="`/usr/bin/sum $(BASE)/$$a`"; \
+	    s2="`/usr/bin/sum $$a`"; \
+            if [ "$$s1" != "$$s2" ]; then \
+	        echo ; \
+	        echo  "ERROR!!! $$a differs in $(BASE), FIXME"; \
+	        echo ; \
+	        exit 1; \
+	    fi; \
+	done
+	@for a in $(MOZYFILES); do \
+	    s1="`/usr/bin/sum $(MOZY)/$$a`"; \
+	    s2="`/usr/bin/sum $$a`"; \
+            if [ "$$s1" != "$$s2" ]; then \
+	        echo ; \
+	        echo  "ERROR!!! $$a differs in $(MOZY), FIXME"; \
+	        echo ; \
+	        exit 1; \
+	    fi; \
+	done
+	@for a in $(SPFILES); do \
+	    s1="`/usr/bin/sum $(SPBASE)/$$a`"; \
+	    s2="`/usr/bin/sum $$a`"; \
+            if [ "$$s1" != "$$s2" ]; then \
+	        echo ; \
+	        echo  "ERROR!!! $$a differs in $(SPBASE), FIXME"; \
+	        echo ; \
+	        exit 1; \
+	    fi; \
+	done
+
diff --git a/wrspice/src/misc/Makefile.in b/wrspice/src/misc/Makefile.in
--- a/wrspice/src/misc/Makefile.in
+++ b/wrspice/src/misc/Makefile.in
@@ -66,4 +66,18 @@ clean:
 distclean: clean
 	-@rm -f Makefile
 
+# Make sure that the copies are the same as the source, avoid local
+# updates that won't propagate!
+cptest::
+	@for a in $(NFILES); do \
+	    s1="`/usr/bin/sum $(BASE)/spnumber/$$a`"; \
+	    s2="`/usr/bin/sum $$a`"; \
+            if [ "$$s1" != "$$s2" ]; then \
+	        echo ; \
+	        echo  "ERROR!!! $$a differs in $(BASE)/spnumber, FIXME"; \
+	        echo ; \
+	        exit 1; \
+	    fi; \
+	done
+
 #######################################################################
diff --git a/wrspice/src/sparse/Makefile.in b/wrspice/src/sparse/Makefile.in
--- a/wrspice/src/sparse/Makefile.in
+++ b/wrspice/src/sparse/Makefile.in
@@ -57,4 +57,18 @@ clean:
 distclean: clean
 	-@rm -f Makefile
 
+# Make sure that the copies are the same as the source, avoid local
+# updates that won't propagate!
+cptest::
+	@for a in $(SP_CCFILES); do \
+	    s1="`/usr/bin/sum $(BASE)/sparse/$$a`"; \
+	    s2="`/usr/bin/sum $$a`"; \
+            if [ "$$s1" != "$$s2" ]; then \
+	        echo ; \
+	        echo  "ERROR!!! $$a differs in $(BASE)/sparse, FIXME"; \
+	        echo ; \
+	        exit 1; \
+	    fi; \
+	done
+
 #######################################################################
diff --git a/xic/src/sparse/Makefile.in b/xic/src/sparse/Makefile.in
--- a/xic/src/sparse/Makefile.in
+++ b/xic/src/sparse/Makefile.in
@@ -53,4 +53,18 @@ clean:
 distclean: clean
 	-@rm -f Makefile
 
+# Make sure that the copies are the same as the source, avoid local
+# updates that won't propagate!
+cptest::
+	@for a in $(CCFILES); do \
+	    s1="`/usr/bin/sum $(BASE)/sparse/$$a`"; \
+	    s2="`/usr/bin/sum $$a`"; \
+            if [ "$$s1" != "$$s2" ]; then \
+	        echo ; \
+	        echo  "ERROR!!! $$a differs in $(BASE)/sparse, FIXME"; \
+	        echo ; \
+	        exit 1; \
+	    fi; \
+	done
+
 #######################################################################
