Moved Makefiles from bin to top in xic/wrspice/mozy.  Updated package files, mozy now has its own package.

diff --git a/wrspice/Makefile.in b/wrspice/Makefile.in
--- a/wrspice/Makefile.in
+++ b/wrspice/Makefile.in
@@ -1,5 +1,5 @@
 #######################################################################
-LOCATION = wrspice/bin
+LOCATION = wrspice
 #######################################################################
 
 DATE = @DATE@
@@ -42,12 +42,10 @@ WINPTHREADFIX = @WINPTHREADFIX@
 TKTOOLS = @TKTOOLS@
 PSLIBS = @PSLIBS@
 
-XIC_PROG = xic
-SPICE_PROG = wrspice
 BUG_ADDR = wrspice@wrcad.com
 ANALYSES = op dc tf ac tran pz disto noise sense
 SPICE_HOST =
-SPICED_LOG = /tmp/$(SPICE_PROG)d.log
+SPICED_LOG = /tmp/wrspiced.log
 DEFAULT_EDITOR = xeditor
 ASCII_RAWFILE = 1
 OPT_CHAR = -
@@ -58,27 +56,23 @@ INSTALL_SCRIPT = $(INSTALL) -c -m 0755
 INSTALL_LIB    = $(INSTALL) -c -m 0644
 INSTALL_LIB_RO = $(INSTALL) -c -m 0444
 
-BASE = ../../xt_base
-SECURE = ../../secure
-VLOG = ../../vl
-INCLUDE = -I../include -I$(BASE)/include -I$(SECURE)
+BASE = ../xt_base
+SECURE = ../secure
+VLOG = ../vl
+INCLUDE = -Iinclude -I$(BASE)/include -I$(SECURE)
 
 WDEMODIR = wrspice_ipc_demo
 
-CCFILES = $(SPICE_PROG).cc $(SPICE_PROG)d.cc multidec.cc \
-    proc2mod.cc printtoraw.cc
-
 SUBDIRS = \
-  ../src/cp ../src/fte ../src/analysis ../src/inp ../src/ckt \
-  ../src/sparse ../src/plot ../src/$(GRPREF)wrs ../src/misc
+  src/cp src/fte src/analysis src/inp src/ckt src/sparse src/plot src/gtkwrs \
+  src/misc
 SUBDIR_LIBS = \
-  ../src/cp/cp.a ../src/fte/fte.a ../src/analysis/analysis.a \
-  ../src/inp/inp.a ../src/ckt/ckt.a ../src/sparse/sparse.a \
-  ../src/plot/plot.a ../src/$(GRPREF)wrs/$(GRPREF)wrs.a \
-  ../src/misc/misc.a
+  src/cp/cp.a src/fte/fte.a src/analysis/analysis.a src/inp/inp.a \
+  src/ckt/ckt.a src/sparse/sparse.a src/plot/plot.a src/gtkwrs/gtkwrs.a \
+  src/misc/misc.a
 
 ifeq ($(USEMOZY), yes)
-MOZY = ../../mozy
+MOZY = ../mozy
 MOZYLIBS1 = $(MOZY)/lib/htm.a $(MOZY)/lib/help.a $(MOZY)/lib/gtkmozy.a \
   $(MOZY)/lib/update_itf.a
 MOZYLIBS2 = $(MOZY)/lib/htm.a $(MOZY)/lib/help.a $(MOZY)/lib/httpget.a \
@@ -86,70 +80,71 @@ MOZYLIBS2 = $(MOZY)/lib/htm.a $(MOZY)/lib/help.a $(MOZY)/lib/httpget.a \
 endif
 
 LOCAL_LIBS = \
-  ../src/cp/cp.a \
-  ../src/fte/fte.a \
+  src/cp/cp.a \
+  src/fte/fte.a \
   $(DEVLIB_CALL) \
-  ../src/analysis/analysis.a \
-  ../src/inp/inp.a \
-  ../src/ckt/ckt.a \
-  ../src/sparse/sparse.a \
-  ../src/plot/plot.a \
-  ../src/$(GRPREF)wrs/$(GRPREF)wrs.a \
+  src/analysis/analysis.a \
+  src/inp/inp.a \
+  src/ckt/ckt.a \
+  src/sparse/sparse.a \
+  src/plot/plot.a \
+  src/$(GRPREF)wrs/$(GRPREF)wrs.a \
   $(SECURE)/secure.a \
   $(MOZYLIBS1) \
   $(BASE)/lib/gtkinterf.a  \
   $(BASE)/lib/ginterf.a \
   $(BASE)/lib/miscutil.a \
   $(MOZYLIBS2) \
-  ../src/misc/misc.a \
+  src/misc/misc.a \
   $(VLOG)/libvlog.a \
   $(NTREGEX)
 
 #######################################################################
 ####### Executable targets ############################################
 
-SPICE_TARGETS = $(SPICE_PROG) $(SPICE_PROG)d multidec proc2mod printtoraw
-all: $(SPICE_TARGETS) wdemo
+TARGETS = wrspice wrspiced multidec proc2mod printtoraw
+all: $(TARGETS) wdemo
+
+$(TARGETS)::
+	$(MAKE) bin/$@
 
 #--------------------
 # The first two targets are for Windows, create wrspice with
 # everything in a DLL, so that we can link plugins against the DLL.
 
-$(DLL_SPICE_PROG): main.cc $(SPICE_PROG).dll
-	$(CC) -o $(SPICE_PROG) main.cc ../src/gtkwrs/resource.o -L. \
-  -l$(SPICE_PROG)
+bin/$(DLL_SPICE_PROG): bin/main.cc bin/wrspice.dll
+	$(CC) -o bin/wrspice bin/main.cc src/gtkwrs/resource.o -L. -lwrspice
 
-$(SPICE_PROG).dll: $(SPICE_PROG).o Makefile $(LOCAL_LIBS) $(MALLOC)
+bin/wrspice.dll: wrspice.o $(LOCAL_LIBS) $(MALLOC)
 	@echo $@: dynamic link
-	@$(LINKCC) $(LSHFLAG) -o $(SPICE_PROG).dll $(LFLAGS) $(SPICE_PROG).o \
+	@$(LINKCC) $(LSHFLAG) -o bin/wrspice.dll $(LFLAGS) bin/wrspice.o \
   $(LOCAL_LIBS) $(LIBS) $(MALLOC) $(STDCLIB)
 
 #--------------------
 
-$(NODLL_SPICE_PROG): $(SPICE_PROG).o Makefile $(LOCAL_LIBS) $(MALLOC)
+bin/$(NODLL_SPICE_PROG): bin/wrspice.o $(LOCAL_LIBS) $(MALLOC)
 	@echo $@: dynamic link
-	@$(LINKCC) -o $(SPICE_PROG) $(LFLAGS) $(SPICE_PROG).o \
+	@$(LINKCC) -o bin/wrspice $(LFLAGS) bin/wrspice.o \
   $(LOCAL_LIBS) $(LIBS) $(MALLOC) $(STDCLIB) $(PSLIBS)
 
-$(SPICE_PROG)d: $(SPICE_PROG)d.o Makefile $(BASE)/lib/miscutil.a
+bin/wrspiced: bin/wrspiced.o $(BASE)/lib/miscutil.a
 	@echo $@: dynamic link
-	@$(LINKCC) -o $(SPICE_PROG)d $(LFLAGS) $(SPICE_PROG)d.o \
+	@$(LINKCC) -o bin/wrspiced $(LFLAGS) bin/wrspiced.o \
   $(BASE)/lib/miscutil.a $(SLIBS) $(STDCLIB) $(WINPTHREADFIX)
 
-multidec: multidec.o ../src/sparse/sparse.a ../src/misc/misc.a Makefile
+bin/multidec: bin/multidec.o src/sparse/sparse.a src/misc/misc.a
 	@echo $@: dynamic link
-	@$(LINKCC) -o multidec multidec.o ../src/sparse/sparse.a \
-  ../src/misc/misc.a $(CURSES) $(STDCLIB) -lm $(WINPTHREADFIX)
+	@$(LINKCC) -o bin/multidec bin/multidec.o src/sparse/sparse.a \
+  src/misc/misc.a $(CURSES) $(STDCLIB) -lm $(WINPTHREADFIX)
 
-proc2mod: proc2mod.o ../src/cp/cp.a ../src/inp/inp.a ../src/misc/misc.a \
-  Makefile
+bin/proc2mod: bin/proc2mod.o src/cp/cp.a src/inp/inp.a src/misc/misc.a
 	@echo $@: dynamic link
-	@$(LINKCC) -o proc2mod proc2mod.o ../src/cp/cp.a ../src/inp/inp.a \
-  ../src/misc/misc.a $(STDCLIB) -lm $(WINPTHREADFIX)
+	@$(LINKCC) -o bin/proc2mod bin/proc2mod.o src/cp/cp.a src/inp/inp.a \
+  src/misc/misc.a $(STDCLIB) -lm $(WINPTHREADFIX)
 
-printtoraw: printtoraw.o $(BASE)/lib/miscutil.a
+bin/printtoraw: bin/printtoraw.o $(BASE)/lib/miscutil.a
 	@echo $@: dynamic link
-	@$(LINKCC) -o printtoraw printtoraw.o $(BASE)/lib/miscutil.a \
+	@$(LINKCC) -o bin/printtoraw bin/printtoraw.o $(BASE)/lib/miscutil.a \
   $(STDCLIB) $(WINPTHREADFIX)
 
 #######################################################################
@@ -221,7 +216,7 @@ ifeq ($(USEMOZY), yes)
 MOZYINC = -I$(MOZY)/include
 endif
 
-$(SPICE_PROG).o: $(SPICE_PROG).cc Makefile
+bin/wrspice.o: bin/wrspice.cc
 	$(CXX) $(CFLAGS) $(INCLUDE) $(MOZYINC) -c \
   -DBDCODE="\"`date +%m%d%y-%H%M%S`"\" \
   -DPREFIX="\"$(prefix)\"" \
@@ -232,8 +227,8 @@ $(SPICE_PROG).o: $(SPICE_PROG).cc Makefile
   -DSPICE_VERSION="\"$(SPICE_VERSION)\"" \
   -DDEVLIB_VERSION="\"$(DEVLIB_VERSION)\"" \
   -DSPICE_BUILD_DATE="\"$(DATE)\"" \
-  -DSPICE_PROG=\"$(SPICE_PROG)\" \
-  -DGFX_PROG="\"$(XIC_PROG)\"" \
+  -DSPICE_PROG=\"wrspice\" \
+  -DGFX_PROG="\"xic\"" \
   -DBUG_ADDR=\"$(BUG_ADDR)\" \
   -DSPICE_NEWS=\"news\" \
   -DSPICE_EDITOR=\"xeditor\" \
@@ -242,27 +237,28 @@ $(SPICE_PROG).o: $(SPICE_PROG).cc Makefile
   -DSPICE_HOST="\"$(SPICE_HOST)\"" \
   -DSPICE_DAEMONLOG="\"$(SPICED_LOG)\"" \
   -DSPICE_NOTICE="\"$(SPICE_NOTICE)\"" \
-  -DAN_`echo $(ANALYSES) |sed -e "s/ / -DAN_/g"` $*.cc
+  -DAN_`echo $(ANALYSES) |sed -e "s/ / -DAN_/g"` \
+  $*.cc
 
-$(SPICE_PROG)d.o: $(SPICE_PROG)d.cc
+bin/wrspiced.o: bin/wrspiced.cc
 	$(CXX) $(CFLAGS) $(INCLUDE) -c \
   -DPREFIX="\"$(prefix)\"" \
   -DTOOLS_ROOT="\"$(TOOLROOT)\"" \
   -DSPICE_DAEMONLOG="\"$(SPICED_LOG)\"" \
-  -DSPICE_PROG="\"$(SPICE_PROG)\"" \
-  $(SPICE_PROG)d.cc
+  -DSPICE_PROG="\"wrspice\"" \
+  $*.cc
 
 .cc.o:
-	$(CXX) $(CFLAGS) $(INCLUDE) -c $*.cc
-
-.c.o:
-	$(CXX) $(CFLAGS) $(INCLUDE) -c $*.c
+	$(CXX) $(CFLAGS) $(INCLUDE) -c $*.cc -o $*.o
 
 #######################################################################
 ####### Dependencies ##################################################
 
+CCFILES = bin/wrspice.cc bin/wrspiced.cc bin/multidec.cc bin/proc2mod.cc \
+  bin/printtoraw.cc
+
 depend:
-	@for a in ../include $(SUBDIRS) ../devlib; do \
+	@for a in include $(SUBDIRS) devlib; do \
 	    (cd $$a; $(MAKE) depend) \
 	done
 	@echo depending in $(LOCATION)
@@ -276,19 +272,18 @@ depend:
 ####### Clean up ######################################################
 
 eclean:
-	-@for a in $(SPICE_TARGETS; do \
-	    rm -f $$a$(NTSUFFIX); \
+	-@for a in $(TARGETS; do \
+	    rm -f bin/$$a$(NTSUFFIX); \
 	done
 
 clean: eclean
 	-@for a in $(SUBDIRS) ../devlib; do \
 	    (cd $$a; $(MAKE) clean) \
 	done
-	-rm -f *.o $(WDEMODIR).tar.gz
+	-rm -f bin/*.o $(WDEMODIR).tar.gz
 
 distclean: eclean
-	-@for a in $(SUBDIRS) ../include ../lib ../devlib ../packages \
-  ../$(WDEMODIR); do \
+	-@for a in $(SUBDIRS) include lib devlib packages $(WDEMODIR); do \
 	    (cd $$a; $(MAKE) distclean) \
 	done
 	-rm -f *.o $(WDEMODIR).tar.gz Makefile
@@ -300,29 +295,33 @@ distclean: eclean
 # examples directory.  This is included in the WRspice distribution.
 
 wdemo wrspice_ipc_demo:
+	if [ ! -f ../xic/src/sced/sced_spiceipc.cc ]; then \
+	    echo "Xic IPC code not found, aborting."; \
+	    exit 1; \
+	fi
 	if [ -d $(WDEMODIR) ]; then \
 	    rm -rf $(WDEMODIR); \
 	fi;
-	cp -pfr ../wrspice_ipc_demo $(WDEMODIR)
+	cp -pfr ipc_demo_files $(WDEMODIR)
 	$(BASE)/util/mvdir $(BASE)/miscutil $(WDEMODIR)/miscutil
 	$(BASE)/util/mvdir $(BASE)/include/miscutil $(WDEMODIR)/miscutil
 	cp -pf $(BASE)/include/config.h.in $(WDEMODIR)/miscutil
 	cp -pf $(BASE)/include/config.h $(WDEMODIR)/miscutil
 	cp -pf $(BASE)/configure.in $(WDEMODIR)
 	cp -pf $(BASE)/configure $(WDEMODIR)
-	cp -pf ../../xic/src/sced/sced_spiceipc.cc $(WDEMODIR)
-	cp -pf ../../xic/include/sced_spiceipc.h $(WDEMODIR)
-	cp -pf wrspiced.cc $(WDEMODIR)
-	cp -pf ../version $(WDEMODIR)
+	cp -pf ../xic/src/sced/sced_spiceipc.cc $(WDEMODIR)
+	cp -pf ../xic/include/sced_spiceipc.h $(WDEMODIR)
+	cp -pf bin/wrspiced.cc $(WDEMODIR)
+	cp -pf version $(WDEMODIR)
 	tar czf $(WDEMODIR).tar.gz $(WDEMODIR)
 	rm -rf $(WDEMODIR)
-	cp -f $(WDEMODIR).tar.gz ../lib/examples
+	cp -f $(WDEMODIR).tar.gz lib/examples
 	@echo
 	@echo "Export source created in $(WDEMODIR).tar.gz"
 	@echo
 
 INSTALL_PREFIX ?= $(prefix)
-destn = $(INSTALL_PREFIX)/$(TOOLROOT)/$(SPICE_PROG)
+destn = $(INSTALL_PREFIX)/$(TOOLROOT)/wrspice
 
 install: install_test install_clean install_bin install_help install_icons \
   install_startup install_scripts install_examples install_docs
@@ -348,89 +347,89 @@ install_clean::
 
 $(destn)/bin::
 	@$(BASE)/util/mkdirpth $@
-	@for aa in $(SPICE_TARGETS); do \
-	    $(INSTALL_BIN) $$aa$(NTSUFFIX) $@; \
+	@for aa in $(TARGETS); do \
+	    $(INSTALL_BIN) bin/$$aa$(NTSUFFIX) $@; \
 	done
-	@if [ $(DLL_SPICE_PROG) = $(SPICE_PROG) ]; then \
-	    $(INSTALL_BIN) $(SPICE_PROG).dll $@; \
+	@if [ $(DLL_SPICE_PROG) = wrspice ]; then \
+	    $(INSTALL_BIN) bin/wrspice.dll $@; \
 	fi
 
 $(destn)/icons::
 	@$(BASE)/util/mkdirpth $@
-	icons=`../packages/util/wrspice_files icons`; \
+	icons=`packages/util/wrspice_files icons`; \
         for a in $$icons; do \
-	    $(INSTALL_LIB) ../lib/icons/$$a $@; \
+	    $(INSTALL_LIB) lib/icons/$$a $@; \
 	done
 
 $(destn)/help::
-	cd ../lib/help; $(MAKE)
+	cd lib/help; $(MAKE)
 	@$(BASE)/util/mkdirpth $@ $@/screenshots
-	help=`../packages/util/wrspice_files help`; \
+	help=`packages/util/wrspice_files help`; \
 	for a in $$help; do \
-	    $(INSTALL_LIB) ../lib/help/$$a $@; \
+	    $(INSTALL_LIB) lib/help/$$a $@; \
 	done
-	helpss=`../packages/util/wrspice_files help_screenshots`; \
+	helpss=`packages/util/wrspice_files help_screenshots`; \
         for a in $$helpss; do \
-	    $(INSTALL_LIB) ../lib/help/screenshots/$$a $@/screenshots; \
+	    $(INSTALL_LIB) lib/help/screenshots/$$a $@/screenshots; \
 	done
 
 $(destn)/startup::
-	cd ../lib/startup; $(MAKE)
+	cd lib/startup; $(MAKE)
 	@$(BASE)/util/mkdirpth $@
-	startup=`../packages/util/wrspice_files startup`; \
+	startup=`packages/util/wrspice_files startup`; \
 	for a in $$startup; do \
-	    $(INSTALL_LIB) ../lib/startup/$$a $@; \
+	    $(INSTALL_LIB) lib/startup/$$a $@; \
 	done
-	klulib=`../packages/util/wrspice_files klu $(OSNAME)`; \
-	if [ -f ../../KLU/$$klulib ]; then \
-	    $(INSTALL_SCRIPT) ../../KLU/$$klulib $@; \
+	klulib=`packages/util/wrspice_files klu $(OSNAME)`; \
+	if [ -f ../KLU/$$klulib ]; then \
+	    $(INSTALL_SCRIPT) ../KLU/$$klulib $@; \
 	fi
 	$(BASE)/util/mkdirpth $@/devices;
-	$(INSTALL_LIB) ../lib/startup/devices/README $@/devices;
+	$(INSTALL_LIB) lib/startup/devices/README $@/devices;
 	for a in $(VLOGMODS); do \
-	    $(INSTALL_LIB) ../devlib/adms/examples/$$a/$$a.$(SOEXT) $@/devices; \
+	    $(INSTALL_LIB) devlib/adms/examples/$$a/$$a.$(SOEXT) $@/devices; \
 	done;
 
 $(destn)/scripts::
 	@$(BASE)/util/mkdirpth $@
-	scripts=`../packages/util/wrspice_files scripts`; \
+	scripts=`packages/util/wrspice_files scripts`; \
 	for a in $$scripts; do \
-	    $(INSTALL_LIB) ../lib/scripts/$$a $@; \
+	    $(INSTALL_LIB) lib/scripts/$$a $@; \
 	done
 
 $(destn)/examples::
 	@$(BASE)/util/mkdirpth $@
-	examples=`../packages/util/wrspice_files examples`; \
+	examples=`packages/util/wrspice_files examples`; \
 	for a in $$examples; do \
-	    $(INSTALL_LIB) ../lib/examples/$$a $@; \
+	    $(INSTALL_LIB) lib/examples/$$a $@; \
 	done
 
 $(destn)/docs::
 	@$(BASE)/util/mkdirpth $@
-	docs=`../packages/util/wrspice_files docs`; \
+	docs=`packages/util/wrspice_files docs`; \
 	for a in $$docs; do \
-	    cp ../lib/docs/$$a $@; \
+	    cp lib/docs/$$a $@; \
 	done
 	IFS="."; \
 	tmp=$(SPICE_VERSION); \
 	set -- $$tmp; \
-	cp ../lib/docs/wrs$$1.$$2 $@
+	cp lib/docs/wrs$$1.$$2 $@
 
 $(destn)/devkit::
 	@$(BASE)/util/mkdirpth $@/admst
 	@$(BASE)/util/mkdirpth $@/include
-	$(INSTALL_LIB) ../devlib/adms/Makefile $@;
-	$(INSTALL_LIB) ../devlib/adms/README $@;
-	$(INSTALL_LIB) ../devlib/adms/README.adms $@;
-	admst=`../packages/util/wrspice_files admst`; \
+	$(INSTALL_LIB) devlib/adms/Makefile $@;
+	$(INSTALL_LIB) devlib/adms/README $@;
+	$(INSTALL_LIB) devlib/adms/README.adms $@;
+	admst=`packages/util/wrspice_files admst`; \
 	for a in $$admst; do \
-	    $(INSTALL_LIB) ../devlib/adms/admst/$$a $@/admst; \
+	    $(INSTALL_LIB) devlib/adms/admst/$$a $@/admst; \
 	done
-	incl=`../packages/util/wrspice_files devincl`; \
+	incl=`packages/util/wrspice_files devincl`; \
 	for a in $$incl; do \
-	    $(INSTALL_LIB) ../devlib/include/$$a $@/include; \
+	    $(INSTALL_LIB) devlib/include/$$a $@/include; \
 	done
-	efiles=`cat ../packages/util/adms_examples`; \
+	efiles=`cat packages/util/adms_examples`; \
 	edirs=""; last=""; \
 	for a in $$efiles; do tifs=$$IFS; IFS=/; set $$a; IFS=$$tifs; \
 	    if [ x$$2 != x -a x$$2 != x$$last -a x$$2 != xREADME -a \
@@ -442,15 +441,15 @@ $(destn)/devkit::
 	    $(BASE)/util/mkdirpth $@/examples/$$a/tests; \
 	done; \
 	for a in $$efiles; do \
-	    $(INSTALL_LIB) ../devlib/adms/$$a $@/`dirname $$a`; \
+	    $(INSTALL_LIB) devlib/adms/$$a $@/`dirname $$a`; \
         done; \
 	for a in $$edirs; do \
-	    cat ../devlib/adms/examples/$$a/Makefile | sed \
+	    cat devlib/adms/examples/$$a/Makefile | sed \
   -e "s%^ADMST = .*%ADMST = /usr/local/xictools/wrspice/devkit/admst%" \
   -e "s%^DLL_LOC = .*%DLL_LOC = /usr/local/xictools/bin%" \
   -e "s%^WRSPICE = .*%WRSPICE = wrspice%" > $@/examples/$$a/Makefile; \
 	    mkdir $@/examples/$$a/module_dist; \
-	    cp ../devlib/adms/examples/$$a/*.$(SOEXT) $@/examples/$$a/module_dist; \
+	    cp devlib/adms/examples/$$a/*.$(SOEXT) $@/examples/$$a/module_dist; \
 	done;
 
 $(destn)/cadence-oasis::
@@ -458,15 +457,15 @@ $(destn)/cadence-oasis::
 
 package::
 	$(MAKE) all
-	(export PATH=`pwd`:$$PATH; cd ../devlib/adms/examples; \
+	(export PATH=`pwd`:$$PATH; cd devlib/adms/examples; \
   $(MAKE) realclean; $(MAKE))
-	-rm -rf ../packages/root
-	mkdir ../packages/root
-	$(MAKE) INSTALL_PREFIX=../packages/root$(prefix) install
-	$(MAKE) INSTALL_PREFIX=../packages/root$(prefix) install_devkit
+	-rm -rf packages/root
+	mkdir packages/root
+	$(MAKE) INSTALL_PREFIX=packages/root$(prefix) install
+	$(MAKE) INSTALL_PREFIX=packages/root$(prefix) install_devkit
 	if [ $(OSNAME) = LinuxRHEL6_64 -o $(OSNAME) = LinuxRHEL7_64 ]; then \
-	    $(MAKE) INSTALL_PREFIX=../packages/root$(prefix) install_cadence; \
+	    $(MAKE) INSTALL_PREFIX=packages/root$(prefix) install_cadence; \
 	fi
-	cd ../packages; $(MAKE) $(SPICE_PROG)-$(OSNAME)
+	cd packages; $(MAKE) wrspice-$(OSNAME)
 
 #######################################################################
